# Time-reversed Diffusion Sampler (DIS)
name: pis
step_size: ${target.pis.step_size}
batch_size: ${target.all.batch_size}
iters: 40000
num_steps: 128
loss: "elbo"  # Currently only supports 'elbo'
grad_clip: 1.
max_diffusion: ${target.pis.max_diffusion}

defaults:
  - model: pisgrad_net
  - noise_schedule: cosine

model:
  bias_init: 1.  # Initialization of the last layers' bias of the time-dependent network
  weight_init: 1e-8  # Initialization of the last layers' weights of the time-dependent network
