name: sonar
dim: 61
has_entropy: False

fn:
  _target_: targets.sonar.Sonar
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: 0.1
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: 1.

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.05, 0.001]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 1.

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 1.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale:  0.1
  step_size: 1e-3

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 1e-3

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  max_diffusion: 1.
  initial_scale: .1
  step_size: 1e-3

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 1.
  initial_scale: .1
  step_size: 1e-3

pis: # Path Integral Sampler
  max_diffusion: 4. # Divided by 4 roughly gives the initial scale
  step_size: 1e-3

dis: # Time-reversed Diffusion Sampler
  initial_scale: 1.
  step_size: 5e-4

dds: # Denoising Diffusion Sampler
  initial_scale: 1.
  step_size: 1e-3

gfn: # Generative Flow Networks
  max_diffusion: 4. # Divided by 4 roughly gives the initial scale
  step_size: 1e-3

gbs:  # General Bridge Sampler
  max_diffusion: 10.
  initial_scale: .1
  step_size: 1e-3

all: # Parameters that are shared between all algorithms
  batch_size: 2000
